language: android

branches:
  only:
    - develop
    - /^release-.*$/
    - /^v\.\d\.\d\.\d$/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.10

jdk:
  - oraclejdk8

android:
  components:
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+

env:
  matrix:
    - COMPILE_METHOD=check
    - COMPILE_METHOD=assembleGithub
    - COMPILE_METHOD=assembleEnterprise

before_script:
  - git submodule update --init

script: ./gradlew $COMPILE_METHOD -PdisablePreDex

deploy:
  provider: releases
  api_key:
    secure: KQU8mdeInl/nc6yQa2ir5nqZcZnoqH06RKDd2nhfIsn8FKvKlVD4b2FUip9EcT0gn5iGzrKXBEBMs8KByiMWMEEF2nI01DwJuhrP/j4PJMyXeYs8TlplEbRXyirJI9drZz1EMfS7AHXuLlQgN8USrRG2THxt6EOP4D4qdJ3tvuc=
  file_glob: true
  file:
  - app/build/outputs/apk/app*.apk
  on:
    tags: true
    all_branches: true
  skip_cleanup: true

notifications:
  slack:
    secure: EzftlFYHtgFuBpRsSleKtsA1PngiK/tKHw8WrFfFU69ehXvvdA1Bi5t+TBn9eFo4E5cRolrPuyMGn8HyMLYn1RFAvr3YcSPIll++92OeyV0C9Opx68aK3iCoIXuasZ0Id3By1mnjefRuQvMQShfHBe/7lbtPvip254H9QX57fl4=
