language: android
sudo: false
android:
  components:
   - build-tools-22.0.1
   - android-22
   - extra-android-m2repository
   - extra-google-google_play_services
   - extra-google-m2repository
  licenses:
    - android-sdk-license-.+

branches:
  only:
    - develop
    - master

notifications:
  email: false
  webhooks:

urls:
      - https://webhooks.gitter.im/e/9234768c960fbc35d489
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

script: ./gradlew assembleDebug
