language: android
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.gradle/native
  - $HOME/.gradle/daemon
  - $HOME/.gradle/caches/jars-1
  - $HOME/.gradle/caches/2.10
jdk:
- oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+
before_script:
- git submodule update --init
script: ./gradlew build -PdisablePreDex
deploy:
- provider: script
  script: ./gradlew publishApkRelease
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: ./gradlew crashlyticsUploadDistributionRelease;
  skip_cleanup: true
  on:
    branch: develop
- provider: releases
  api_key:
    secure: e8vh46Ei3Xf1KUk/+8UP0wXcIgqtuPLj2cZY3PdUCCo8C8Kc6xmtMRH6yAiNG0b02GmJf/yLn2MXJvC9spVf+vsGDtl+cqB4qBdaF9Ei5ekf1X+X3cjW9t6NR3acj85mxC4EjeIodO81PCcrJ+BZBHzEbi4Zy0HADfHuxTOHxwE=
  file: apps/Gitskarios/app/build/outputs/apk/app-debug.apk
  on:
    tags: true
    all_branches: true
notifications:
  slack:
    secure: EzftlFYHtgFuBpRsSleKtsA1PngiK/tKHw8WrFfFU69ehXvvdA1Bi5t+TBn9eFo4E5cRolrPuyMGn8HyMLYn1RFAvr3YcSPIll++92OeyV0C9Opx68aK3iCoIXuasZ0Id3By1mnjefRuQvMQShfHBe/7lbtPvip254H9QX57fl4=
before_install:
- openssl aes-256-cbc -K $encrypted_7d926816f25e_key -iv $encrypted_7d926816f25e_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar