language: android
sudo: false
android:
  components:
   - build-tools-22.0.1
   - android-22
   - extra-android-m2repository
   - extra-google-google_play_services
   - extra-google-m2repository
  licenses:
    - android-sdk-license-.+

branches:
  only:
    - develop
    - master

notifications:
  email: false

script: ./gradlew assembleDebug
